### ISSUE TITLE
Shooting stars

### ISSUE THREAD

**Issue by cadekynaston** [richardtaylordawson/bruner-dynamics#11]
Make it like mikes

**Comment by richardtaylordawson** [comment]
Thank you. I will look into this

**Comment by carstonhenderson** [comment]
Not working for me. When will this be fixed?

**Comment by richardtaylordawson** [comment]
@carstonhenderson I am hoping to fix this by version 26.7.0 thank you for your patience

**Comment by carstonhenderson** [comment]
My company depends on this in production. I will fork and just do it myself

**Comment by richardtaylordawson** [comment]
@carstonhenderson I totally understand your frustration. Bruner Dynamics from the get go was meant to be for other companies production builds and giving others the absolute best and most positive experience I can, unfortunately I'm not a contributor to major open source projects like React or Tailwind and so I fear my skills are lacking to provide such a scope
